server:
  port: 5001
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: API-KEY
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    #    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/areastory
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  redis:
#    host: ${REDIS_URL}
#    port: ${REDIS_PORT}

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      access-key: ${ACCESS-KEY}
      secret-key: ${SECRET-KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false