server:
  servlet:
    contextPath: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 5003
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ${DB_PASSWORD}
      username: ${DB_USER}
    url: ${DB_URL}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER